h=df["studytime"].value_counts()
r=h.tolist()
print(r)
o=df.groupby("studytime")['G3'].mean()
list1=o.tolist()
print(list1)
plt.scatter(list1,r,color='red',marker='o')
plt.title("Performance & Study Habits")
plt.xlabel("study_time")
plt.ylabel("affect_final_grades")
plt.show()